from pr_review_bot.github_client import PRInfo
from datetime import datetime


def format_github_comment(review_text: str, pr_info: PRInfo, repo: str) -> str:
    """
    Format the review text into a polished GitHub comment.
    GitHub renders markdown so we can use full formatting.
    """

    # Header with metadata
    header = f"""## 🤖 Automated PR Review

> **Generated by [PR Review Bot](https://github.com/YOUR_USERNAME/pr-review-bot)**
> Using **Groq + Llama 3** | Reviewed at {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}

| | |
|---|---|
| **PR** | #{pr_info.number} — {pr_info.title} |
| **Author** | @{pr_info.author} |
| **Files Reviewed** | {len([f for f in pr_info.files if f.patch])} |
| **Changes** | +{pr_info.total_additions} / -{pr_info.total_deletions} |

---

"""

    # Footer
    footer = """

---
<details>
<summary>ℹ️ About this review</summary>

This review was generated automatically by analyzing the PR diff using 
Llama 3 (70B) via Groq. It may not catch all issues — always use your 
own judgment. To run this tool yourself, see the 
[PR Review Bot repo](https://github.com/YOUR_USERNAME/pr-review-bot).

</details>"""

    return header + review_text + footer


def format_duplicate_warning(existing_count: int) -> str:
    """Message shown when bot has already reviewed this PR"""
    return (
        f"⚠️  This PR already has {existing_count} bot review(s).\n"
        f"Use --force to post another review anyway."
    )